package in.nareshit.raghu.rest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import in.nareshit.raghu.model.User;
import in.nareshit.raghu.request.UserRequest;
import in.nareshit.raghu.response.UserResponse;
import in.nareshit.raghu.service.IUserService;
import in.nareshit.raghu.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {
	
	@Autowired
	private AuthenticationManager authenticationManager;

	@Autowired
	private JwtUtil util;
	
	@Autowired
	private IUserService service;
	
	@PostMapping("/save")
	public ResponseEntity<String> saveUser(
			@RequestBody User user) 
	{
		Integer id = service.saveUser(user);
		return ResponseEntity.ok("User created!!" + id);
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(
			@RequestBody UserRequest userRequest
			) 
	{
		
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						userRequest.getUsername(), userRequest.getPassword())
				);
		
		String token = util.generateToken(userRequest.getUsername());
		return ResponseEntity.ok(new UserResponse(token, "GENERATED BY RAGHU NIT"));
	}
	
	@PostMapping("/home")
	public ResponseEntity<String> securedResource()
	{
		return ResponseEntity.ok("WELCOME TO SECURED RESOURCE AFTER LOGIN!");
	}
	
}
